name: Android CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v2.3.4
      - name: Setup JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 1.8
      - name: Build Project
        run: ./gradlew assemble
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.4
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk